server:
  port: 8080

spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: WP Control
    title: ${project.description}
    version: ${project.version}
    java: ${project.sourceCompatibility}
  main:
    banner-mode: "console"

logging:
  file: /PerfLogs/api-bankAccount.log
  level:
    root: info