FROM openjdk:8
EXPOSE 8080
ADD build/libs/api-bank-account-0.0.1-SNAPSHOT.jar api-bank-account-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "api-bank-account-0.0.1-SNAPSHOT.jar"]

##RUN mkdir home/abdiel/projects
##COPY
##WORKDIR home/abdiel/projects

